export default function ChatContainer() {
  return (
    <div className="p-4 chat-container overflow-auto">
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
      <h1>Chat Container</h1>
    </div>
  );
}
