import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import Sidebar from '@/components/template/sidebar';
import MainContent from './mainContent';
import { Providers } from './providers';

const inter = Inter({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  title: 'Chat - Gabut',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main>
            <Sidebar />
            <MainContent>
              {children}
            </MainContent>
          </main>
        </Providers>
      </body>
    </html>
  );
}
